radiacode app sometimes mis-identifies the device
sandialabs/SpecUtils pull request #20
Opened 2024-01-05 00:40 UTC by ckuethe

This diff adds a check based on the serial number; if a discrepancy is found the `instrument_model_` field is patched to the assumed model. As best I can tell, the rest of the spectrum output is correct.

Example files for test suite sent separately.

2024-01-05 19:36 UTC, ckuethe commented
![Screenshot_2024-01-04_22-45-46](https://github.com/sandialabs/SpecUtils/assets/1131751/53f22261-773c-496c-8276-f9f9ab581459)

Using one of the test files and locally compiled interspec, we can see that the warning is propagated up. The fix-up was performed correctly, but/and this does not seem like a thing that should just happen silently.

2024-01-05 22:14 UTC, wcjohns requested changes
Thanks for making this change Chris!

A few comments:
- The `instrument_id_.substr(2,4);` call may fail if the string is not long enough.
- Would it make sense to check that the "X" of "-00X" in `model_num` is a number, and that the string starts with "-00"?
- I think as long as the checks suggested in the previous step pass, than maybe its best to not bother the user with the warning, since this is a known issue in the radiacode files, which you are correcting for here.  Thoughts?

2024-01-06 00:43 UTC, ckuethe commented
In general, I prefer it when a program tells me "hey, I found a weird thing in your data file. It's not a big problem, but you should probably figure out where that came from." I've got a number of other unrelated apps that do the same thing. They have consistency checks and will let you know if the some part of the input seems a little odd, but they'll try their best to process the input in the absence of a critical error. Silently papering these things over feels a little icky to me.

I've filed a bug report so hopefully the issue will be corrected soon. There may be a second bug, or it's different from what I think it is, since I have examples of an RC-102 being reported as both a 101 and a 103 and I've never had a 101.

If `instrument_id_.substr(2,4)` fails there are bigger problems. I'm now using a regex to check that the serial number format is correct. If it doesn't match `RC-[0-9]{3}-[0-9]{6}`, something has gone very wrong and I no longer trust it. I'll update the regex if we see new devices in the wild.

2024-01-06 06:22 UTC, wcjohns approved these changes
Thank you for implementing this Chris!

2024-01-06 06:22 UTC, merged

2024-01-06 06:34 UTC, wcjohns commented
That was a good idea to pester developers with the warning when there is a mismatch, but not necessarily bother users.
I guess I had assumed the model identification from the serial number should always be correct, is this the case?  If so, then yes, lets not bother users (like you have it).


Looking at things a second time, should the line:
```
if ( instrument_id_.find( model_from_sn ) == string::npos)
```

maybe instead be

```
if ( instrument_model_.find( model_from_sn ) == string::npos)
```
?

2024-01-06 06:54 UTC, ckuethe commented
Yes, good catch.

2024-01-06 07:00 UTC, ckuethe commented
Using the code as of [fe7ce21](https://github.com/sandialabs/SpecUtils/commit/fe7ce21cc03c0f3664ca6a20bb14e42ad4c6ed43) works as I intend:

this has an invalid serial number (I deleted the last digit) and the device identification isn't fixed up
![Screenshot_2024-01-05_22-57-45](https://github.com/sandialabs/SpecUtils/assets/1131751/718a66af-2491-41fa-bc0a-8249e933a9ee)

This has a valid serial number so the fixup code runs.
![Screenshot_2024-01-05_22-57-19](https://github.com/sandialabs/SpecUtils/assets/1131751/54f0fed2-9fa3-47b3-9a83-2109c4a700dd)

2024-01-06 17:58 UTC, wcjohns commented
Thanks for fixing this!